### PR TITLE
Overlapping LLR + ADMM update scheme

### PR DESCRIPTION
**Pull request by JakobAsslaender**
Hi,
I implemented a few things in this PR (sorry for not separating them):
1. I implemented a proximal function for overlapping LLR
2. I multi-threaded the LLR proximal
3. I added a second update scheme for the ADMM algorithm which has proofen more robust for our use-case. 

The first two changes are non-breaking and there should not really be any downside. The last one is breaking as I changed the keyword argument `vary_rho` from type `Boolean` to `Symbol` to facilitate the 3-way option. Also, this update scheme does come at a small price: we have to store a "old" version of `x` and `u`--a reasonable price if IMHO, but that is, of course, subjective. 

LMK what you think!

### CODE REVIEW

**Comment by tknopp** [comment]
Regarding multi-threading I don't use Polyester anymore since it can lead to issues with the regular Julia thread pool. In particular it can make FFTW slower: https://github.com/JuliaSIMD/Polyester.jl/issues/63. Instead please use https://github.com/JuliaFolds/FLoops.jl, which makes no problems und uses the regular Julia thread pool. I already use it in NFFT.jl and we will soon switch in MRIReco.jl as well.

**Comment by tknopp** [comment]
@migrosser: Could you please have a look at the interface change (point 3) and comment if this breaks code somewhere? By bumping the version number this can be handled without too much problems IMHO.

**Comment by migrosser** [comment]
I think the interface change looks fine and I am not aware of any code that it would break. 
A small proposal from my side would by to document the possible values for `vary_rho` in the doc-string of the solver. I know that we are often somewhat lazy when it comes to documentation, but this would make it easier to grasp the possible options.

**Comment by JakobAsslaender** [comment]
@tknopp : The point re Polyester is interesting I will keep that in mind for all packages. The problem with `Threads.@threads` is that this actually caused reproducible segfault errors in BLAS (I am assuming during the SVD, the error message is not clear though). I can try out Floops, but if it uses Threads, I would assume it has the same problems.

@migrosser : Yes, documentation is definitely not great yet. I am swamped for next month, but I add it some time in June, but feel free to add it if you want it earlier! I was contemplating about a change of the interface anyways to a) harmonize it with InterativeSolvers.jl and b) allow calculating the back projection a-priori. Essentially, I was thinking--in line with InterativeSolvers.jl, that it might make sense to consider only AHA operator within the algorithm. I think this would a) make sense from a mathematical perspective and b) would allow one to, calculate the back projection, delete the data, and then calculate, e.g. Toeplitz kernel, which minimizes memory usage. Further, it means that one does not have build the operator `A` and implement or fake its forward multiplication if one has an implementation for `AHA`. But again, from my end we are talking at least June....

**Comment by tknopp** [comment]
Threading situation is complicated right now. As far as I recall, `Threads.@threads` does not work with the new threading runtime (partr), which might cause the issue. `FLoops` uses the partr and hopefully should be fine. I actually consulted people in the multi-threading slack of Julia when investigating this.

**Pull request merged**
