### PR TITLE
bugfix to make FISTA compatible with LinearOperators.jl v2

### PR DESCRIPTION
**Pull request by JakobAsslaender**
Hi,
It seems that LinearOperators.jl v2 uses the `mul!` functions as part of their type definition. Therefore, `A` and `AHA` have no longer the same type. This PR fixes this issue for FISTA. In ADMM, this should be fine since they are already of different type.

### CODE REVIEW

**Comment by tknopp** [comment]
Thanks. I wonder though, if we should take this approach in general or better do what we do with CGNR. There we automatically calculate the normal operator: https://github.com/tknopp/RegularizedLeastSquares.jl/blob/master/src/CGNR.jl#L73

**Comment by JakobAsslaender** [comment]
Not sure that I like this: It ties `A` very closely to `AHA`, and, for example, my current reconstructions constructs an `AHA` operator that uses the Toeplitz structure, and I don't really construct `A` at all:
```
xbp = A' * vec(data)
```
or
```
xbp = my_backprojection(data)
x = zeros(ComplexF32, length(xbp))
cg!(x, AᴴA, vec(xbp))
```
I like that approach quite a lot, I must say. This way you can even delete the data before starting you iterations, which can be beneficial when being memory constraint since you never have to store the k-space data and the Toeplitz Kernels at the same time. 

When using the FISTA or ADMM implementation, I write a "fake" operator `A` that can only has the adjoint defined. With LingeraOperators.jl v2 this is actually a bit ugly, as it requires a forward operation, which I have to fake.

**Comment by tknopp** [comment]
> Further, the implementation in CGNR requires SparsityOperators.jl and, IMHO, we should decouple those two packages.

Indeed, I actually tried getting rid of the directly dependency and `normalOperator` was a show stopper.
On the other hand having an operator library is very useful when you think about the regularizers. There, I don't want to manually build up the regularizers but use them ready-to-go. 

 I will need to think a little bit about the issue with `normalOperator`. Would be interesting to find out what would need to change in MRIReco if we take the approach we do with `FISTA` and `ADMM`.

**Comment by JakobAsslaender** [comment]
I would suggest to move these convinces tools to MRIReco. This would, IMHO, be the perfect place to combine all the packages. But we can get rid of dependencies of SparsityOperators.jl, and maybe even LinerarOperators.jl, this package would be much more generic, both for ppl outside of imaging, but maybe we should also talk to @JeffFessler, if he would be willing to contribute to a modular zoo of Julia packages and merge his fancy FISTA versions etc.

**Pull request merged**
